import 'vital_category.dart';
import 'vital_type.dart';

extension VitalTypeExtension on VitalType {
  VitalCategory get category => <VitalType, VitalCategory>{
        VitalType.fastingBloodSugar: VitalCategory.bloodSugar,
        VitalType.hba1c: VitalCategory.bloodSugar,
        VitalType.avgBloodGlucose: VitalCategory.bloodSugar,
        VitalType.totalCholesterol: VitalCategory.lipids,
        VitalType.hdlCholesterol: VitalCategory.lipids,
        VitalType.ldlCholesterol: VitalCategory.lipids,
        VitalType.triglycerides: VitalCategory.lipids,
        VitalType.vldlCholesterol: VitalCategory.lipids,
        VitalType.nonHdlCholesterol: VitalCategory.lipids,
        VitalType.tcHdlRatio: VitalCategory.lipids,
        VitalType.tsh: VitalCategory.thyroid,
        VitalType.t3: VitalCategory.thyroid,
        VitalType.t4: VitalCategory.thyroid,
        VitalType.vitaminD: VitalCategory.vitaminsAndIron,
        VitalType.vitaminB12: VitalCategory.vitaminsAndIron,
        VitalType.serumIron: VitalCategory.vitaminsAndIron,
        VitalType.tibc: VitalCategory.vitaminsAndIron,
        VitalType.transferrinSat: VitalCategory.vitaminsAndIron,
        VitalType.sgot: VitalCategory.liver,
        VitalType.sgpt: VitalCategory.liver,
        VitalType.ggt: VitalCategory.liver,
        VitalType.alkalinePhosphatase: VitalCategory.liver,
        VitalType.bilirubinTotal: VitalCategory.liver,
        VitalType.serumAlbumin: VitalCategory.liver,
        VitalType.serumCreatinine: VitalCategory.kidney,
        VitalType.uricAcid: VitalCategory.kidney,
        VitalType.egfr: VitalCategory.kidney,
        VitalType.bun: VitalCategory.kidney,
        VitalType.calcium: VitalCategory.kidney,
        VitalType.hemoglobin: VitalCategory.bloodCount,
        VitalType.hematocrit: VitalCategory.bloodCount,
        VitalType.wbcCount: VitalCategory.bloodCount,
        VitalType.plateletCount: VitalCategory.bloodCount,
        VitalType.mcv: VitalCategory.bloodCount,
        VitalType.sodium: VitalCategory.electrolytes,
        VitalType.chloride: VitalCategory.electrolytes,
        VitalType.heartRate: VitalCategory.vitalsAndWearable,
        VitalType.bloodPressureSystolic: VitalCategory.vitalsAndWearable,
        VitalType.bloodPressureDiastolic: VitalCategory.vitalsAndWearable,
        VitalType.spO2: VitalCategory.vitalsAndWearable,
        VitalType.hrv: VitalCategory.vitalsAndWearable,
        VitalType.bodyWeight: VitalCategory.vitalsAndWearable,
        VitalType.heightCm: VitalCategory.vitalsAndWearable,
        VitalType.bmi: VitalCategory.vitalsAndWearable,
        VitalType.bodyTemperature: VitalCategory.vitalsAndWearable,
      }[this]!;

  String get displayName => <VitalType, String>{
        VitalType.fastingBloodSugar: 'Fasting Blood Sugar',
        VitalType.hba1c: 'HbA1c',
        VitalType.avgBloodGlucose: 'Avg Blood Glucose',
        VitalType.totalCholesterol: 'Total Cholesterol',
        VitalType.hdlCholesterol: 'HDL Cholesterol',
        VitalType.ldlCholesterol: 'LDL Cholesterol',
        VitalType.triglycerides: 'Triglycerides',
        VitalType.vldlCholesterol: 'VLDL Cholesterol',
        VitalType.nonHdlCholesterol: 'Non-HDL Cholesterol',
        VitalType.tcHdlRatio: 'TC/HDL Ratio',
        VitalType.tsh: 'TSH',
        VitalType.t3: 'T3 (Triiodothyronine)',
        VitalType.t4: 'T4 (Thyroxine)',
        VitalType.vitaminD: 'Vitamin D',
        VitalType.vitaminB12: 'Vitamin B12',
        VitalType.serumIron: 'Serum Iron',
        VitalType.tibc: 'TIBC',
        VitalType.transferrinSat: 'Transferrin Saturation',
        VitalType.sgot: 'SGOT (AST)',
        VitalType.sgpt: 'SGPT (ALT)',
        VitalType.ggt: 'GGT',
        VitalType.alkalinePhosphatase: 'Alkaline Phosphatase',
        VitalType.bilirubinTotal: 'Bilirubin (Total)',
        VitalType.serumAlbumin: 'Serum Albumin',
        VitalType.serumCreatinine: 'Creatinine',
        VitalType.uricAcid: 'Uric Acid',
        VitalType.egfr: 'eGFR',
        VitalType.bun: 'Blood Urea Nitrogen',
        VitalType.calcium: 'Calcium',
        VitalType.hemoglobin: 'Hemoglobin',
        VitalType.hematocrit: 'Hematocrit (PCV)',
        VitalType.wbcCount: 'WBC Count',
        VitalType.plateletCount: 'Platelet Count',
        VitalType.mcv: 'MCV',
        VitalType.sodium: 'Sodium',
        VitalType.chloride: 'Chloride',
        VitalType.heartRate: 'Heart Rate',
        VitalType.bloodPressureSystolic: 'Blood Pressure (Systolic)',
        VitalType.bloodPressureDiastolic: 'Blood Pressure (Diastolic)',
        VitalType.spO2: 'Blood Oxygen (SpO₂)',
        VitalType.hrv: 'Heart Rate Variability',
        VitalType.bodyWeight: 'Body Weight',
        VitalType.heightCm: 'Height',
        VitalType.bmi: 'BMI',
        VitalType.bodyTemperature: 'Body Temperature',
      }[this]!;

  String get unit => <VitalType, String>{
        VitalType.fastingBloodSugar: 'mg/dL',
        VitalType.hba1c: '%',
        VitalType.avgBloodGlucose: 'mg/dL',
        VitalType.totalCholesterol: 'mg/dL',
        VitalType.hdlCholesterol: 'mg/dL',
        VitalType.ldlCholesterol: 'mg/dL',
        VitalType.triglycerides: 'mg/dL',
        VitalType.vldlCholesterol: 'mg/dL',
        VitalType.nonHdlCholesterol: 'mg/dL',
        VitalType.tcHdlRatio: 'ratio',
        VitalType.tsh: 'µIU/mL',
        VitalType.t3: 'ng/dL',
        VitalType.t4: 'µg/dL',
        VitalType.vitaminD: 'ng/mL',
        VitalType.vitaminB12: 'pg/mL',
        VitalType.serumIron: 'µg/dL',
        VitalType.tibc: 'µg/dL',
        VitalType.transferrinSat: '%',
        VitalType.sgot: 'U/L',
        VitalType.sgpt: 'U/L',
        VitalType.ggt: 'U/L',
        VitalType.alkalinePhosphatase: 'U/L',
        VitalType.bilirubinTotal: 'mg/dL',
        VitalType.serumAlbumin: 'gm/dL',
        VitalType.serumCreatinine: 'mg/dL',
        VitalType.uricAcid: 'mg/dL',
        VitalType.egfr: 'mL/min/1.73m²',
        VitalType.bun: 'mg/dL',
        VitalType.calcium: 'mg/dL',
        VitalType.hemoglobin: 'g/dL',
        VitalType.hematocrit: '%',
        VitalType.wbcCount: '×10³/µL',
        VitalType.plateletCount: '×10³/µL',
        VitalType.mcv: 'fL',
        VitalType.sodium: 'mmol/L',
        VitalType.chloride: 'mmol/L',
        VitalType.heartRate: 'bpm',
        VitalType.bloodPressureSystolic: 'mmHg',
        VitalType.bloodPressureDiastolic: 'mmHg',
        VitalType.spO2: '%',
        VitalType.hrv: 'ms',
        VitalType.bodyWeight: 'kg',
        VitalType.heightCm: 'cm',
        VitalType.bmi: 'kg/m²',
        VitalType.bodyTemperature: '°C',
      }[this]!;

  bool get isWearableSourced => <VitalType>[
        VitalType.heartRate,
        VitalType.spO2,
        VitalType.hrv,
        VitalType.bloodPressureSystolic,
        VitalType.bloodPressureDiastolic,
      ].contains(this);

  bool get isDerived => <VitalType>[
        VitalType.avgBloodGlucose,
        VitalType.nonHdlCholesterol,
        VitalType.tcHdlRatio,
        VitalType.bmi,
      ].contains(this);
}
