import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../../../shared/widgets/glass_card.dart';
import '../../../../shared/widgets/shimmer_loading.dart';
import '../../domain/entities/daily_briefing.dart';
import '../providers/insights_providers.dart';

/// Full or compact morning briefing from [dailyBriefingProvider].
class DailyBriefingCard extends ConsumerWidget {
  const DailyBriefingCard({super.key, this.compact = false, this.onTapSeeAll});

  final bool compact;
  final VoidCallback? onTapSeeAll;

  static String greetingHeader() {
    final int h = DateTime.now().hour;
    if (h < 12) {
      return 'Good morning! 🌅';
    }
    if (h < 17) {
      return 'Good afternoon! ☀️';
    }
    return 'Good evening! 🌙';
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final AsyncValue<DailyBriefing> async = ref.watch(dailyBriefingProvider);

    return async.when(
      loading: () =>
          GlassCard(child: compact ? _compactLoading() : _fullLoading()),
      error: (Object e, StackTrace _) => GlassCard(
        child: InkWell(
          onTap: () => ref.invalidate(dailyBriefingProvider),
          borderRadius: BorderRadius.circular(16),
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 4),
            child: Text(
              'Couldn\'t generate briefing. Tap to retry.',
              style: AppTextStyles.bodyMedium.copyWith(color: AppColors.error),
            ),
          ),
        ),
      ),
      data: (DailyBriefing b) => GlassCard(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: <Widget>[
                      Text(
                        greetingHeader(),
                        style: AppTextStyles.headlineMedium.copyWith(
                          fontSize: compact ? 18 : 20,
                        ),
                      ),
                      const SizedBox(height: 8),
                      Text(
                        b.morningText,
                        style: AppTextStyles.bodyLarge,
                        maxLines: compact ? 2 : null,
                        overflow: compact ? TextOverflow.ellipsis : null,
                      ),
                    ],
                  ),
                ),
                IconButton(
                  tooltip: 'Refresh',
                  onPressed: () => ref
                      .read(dailyBriefingProvider.notifier)
                      .refreshBriefing(),
                  icon: const Icon(Icons.refresh_rounded),
                  color: AppColors.secondary,
                ),
              ],
            ),
            const SizedBox(height: 10),
            Row(
              children: <Widget>[
                Text(
                  DateFormat.yMMMd().format(b.generatedAt),
                  style: AppTextStyles.bodySmall,
                ),
                const SizedBox(width: 8),
                Text('·', style: AppTextStyles.bodySmall),
                const SizedBox(width: 8),
                Text(
                  'Generated by Gemini Flash',
                  style: AppTextStyles.bodySmall,
                ),
              ],
            ),
            if (compact && onTapSeeAll != null) ...<Widget>[
              const SizedBox(height: 12),
              Align(
                alignment: Alignment.centerRight,
                child: TextButton(
                  onPressed: onTapSeeAll,
                  child: Text(
                    'See Full Insights →',
                    style: AppTextStyles.labelLarge.copyWith(
                      color: AppColors.secondary,
                    ),
                  ),
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _fullLoading() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const ShimmerLoading(height: 22),
        const SizedBox(height: 12),
        const ShimmerLoading(height: 14),
        const SizedBox(height: 8),
        const ShimmerLoading(height: 14),
        const SizedBox(height: 8),
        const ShimmerLoading(height: 14),
      ],
    );
  }

  Widget _compactLoading() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        const ShimmerLoading(height: 18),
        const SizedBox(height: 10),
        const ShimmerLoading(height: 12),
        const SizedBox(height: 8),
        const ShimmerLoading(height: 12),
      ],
    );
  }
}
