import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_text_styles.dart';
import '../../domain/entities/correlation_alert.dart';
import '../../domain/entities/weekly_report.dart';
import '../providers/insights_providers.dart';
import '../widgets/correlation_alert_card.dart';
import '../widgets/module_insight_tab.dart';
import '../widgets/weekly_report_section_card.dart';

/// Full weekly holistic report (Gemini Pro).
class WeeklyReportScreen extends ConsumerStatefulWidget {
  const WeeklyReportScreen({super.key});

  @override
  ConsumerState<WeeklyReportScreen> createState() => _WeeklyReportScreenState();
}

class _WeeklyReportScreenState extends ConsumerState<WeeklyReportScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabs;

  static const List<String> _tabKeys = <String>[
    'Activity',
    'Diet',
    'Workout',
    'Health',
    'Mental',
  ];

  @override
  void initState() {
    super.initState();
    _tabs = TabController(length: _tabKeys.length, vsync: this);
  }

  @override
  void dispose() {
    _tabs.dispose();
    super.dispose();
  }

  String _weekTitle(WeeklyReport r) {
    final DateTime start = r.weekStarting;
    final DateTime end = start.add(const Duration(days: 6));
    return 'Week of ${DateFormat.MMMd().format(start)} – '
        '${DateFormat.MMMd().format(end)}';
  }

  @override
  Widget build(BuildContext context) {
    final AsyncValue<WeeklyReport> async = ref.watch(weeklyReportProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.surfaceContainer,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
        title: async.when(
          data: (WeeklyReport r) => Text(
            _weekTitle(r),
            style: AppTextStyles.headlineMedium.copyWith(fontSize: 16),
          ),
          loading: () => Text(
            'Weekly report',
            style: AppTextStyles.headlineMedium.copyWith(fontSize: 16),
          ),
          error: (_, __) => Text(
            'Weekly report',
            style: AppTextStyles.headlineMedium.copyWith(fontSize: 16),
          ),
        ),
        bottom: async.maybeWhen(
          data: (WeeklyReport r) => r.isPlaceholder
              ? null
              : TabBar(
                  controller: _tabs,
                  isScrollable: true,
                  labelStyle: AppTextStyles.labelSmall,
                  unselectedLabelColor: AppColors.onSurfaceVariant,
                  indicatorColor: AppColors.secondary,
                  tabs: _tabKeys.map((String k) => Tab(text: k)).toList(),
                ),
          orElse: () => null,
        ),
      ),
      body: async.when(
        data: (WeeklyReport r) {
          if (r.isPlaceholder) {
            return Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Text(
                      r.executiveSummary,
                      style: AppTextStyles.bodyLarge,
                      textAlign: TextAlign.center,
                    ),
                    const SizedBox(height: 24),
                    FilledButton(
                      onPressed: () => ref
                          .read(weeklyHolisticReportProvider.notifier)
                          .generateThisWeekReport(),
                      child: const Text('Generate this week'),
                    ),
                  ],
                ),
              ),
            );
          }
          return ListView(
            padding: const EdgeInsets.fromLTRB(20, 16, 20, 32),
            children: <Widget>[
              WeeklyReportSectionCard(
                title: 'Your Week at a Glance',
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(r.executiveSummary, style: AppTextStyles.bodyLarge),
                    const SizedBox(height: 10),
                    Text(
                      'Generated by Gemini Pro • Updated Sunday',
                      style: AppTextStyles.bodySmall,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),
              WeeklyReportSectionCard(
                title: '🏆 Wins This Week',
                titleColor: AppColors.primaryContainer,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: r.wins.isEmpty
                      ? <Widget>[
                          Text(
                            'No wins listed yet.',
                            style: AppTextStyles.bodyMedium,
                          ),
                        ]
                      : r.wins
                            .map(
                              (String w) => Padding(
                                padding: const EdgeInsets.only(bottom: 8),
                                child: Row(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    const Icon(
                                      Icons.check_circle_outline,
                                      size: 20,
                                      color: AppColors.primaryContainer,
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        w,
                                        style: AppTextStyles.bodyLarge,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            )
                            .toList(),
                ),
              ),
              const SizedBox(height: 16),
              WeeklyReportSectionCard(
                title: '📍 Areas to Focus On',
                titleColor: AppColors.warningAmber,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: r.focusAreas.isEmpty
                      ? <Widget>[
                          Text(
                            'No focus areas listed.',
                            style: AppTextStyles.bodyMedium,
                          ),
                        ]
                      : r.focusAreas
                            .map(
                              (String f) => Padding(
                                padding: const EdgeInsets.only(bottom: 8),
                                child: Row(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    const Icon(
                                      Icons.arrow_forward_ios_rounded,
                                      size: 14,
                                      color: AppColors.warningAmber,
                                    ),
                                    const SizedBox(width: 8),
                                    Expanded(
                                      child: Text(
                                        f,
                                        style: AppTextStyles.bodyLarge,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            )
                            .toList(),
                ),
              ),
              const SizedBox(height: 16),
              Text('Module breakdown', style: AppTextStyles.labelLarge),
              const SizedBox(height: 8),
              SizedBox(
                height: 220,
                child: TabBarView(
                  controller: _tabs,
                  children: _tabKeys
                      .map(
                        (String k) =>
                            ModuleInsightTab(text: r.moduleInsights[k] ?? ''),
                      )
                      .toList(),
                ),
              ),
              const SizedBox(height: 24),
              Text(
                'Cross-Module Insights',
                style: AppTextStyles.headlineMedium.copyWith(fontSize: 18),
              ),
              const SizedBox(height: 12),
              if (r.crossModuleInsights.isEmpty)
                Text(
                  'No additional cross-module notes.',
                  style: AppTextStyles.bodySmall,
                )
              else
                ...r.crossModuleInsights.map(
                  (CorrelationAlert a) => Padding(
                    padding: const EdgeInsets.only(bottom: 12),
                    child: CorrelationAlertCard(alert: a),
                  ),
                ),
              const SizedBox(height: 16),
              WeeklyReportSectionCard(
                title: 'Goal progress',
                child: Text(r.goalProgressText, style: AppTextStyles.bodyLarge),
              ),
              const SizedBox(height: 20),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                  onPressed: null,
                  child: Text(
                    'Share Report',
                    style: AppTextStyles.button.copyWith(
                      color: AppColors.onSurfaceVariant,
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 8),
              Text(
                'Sharing will be available in a future update.',
                style: AppTextStyles.bodySmall,
                textAlign: TextAlign.center,
              ),
            ],
          );
        },
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (Object e, StackTrace _) => Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: <Widget>[
                Text(
                  'Could not load this week\'s report.',
                  style: AppTextStyles.bodyLarge,
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: 16),
                FilledButton(
                  onPressed: () => ref.invalidate(weeklyHolisticReportProvider),
                  child: const Text('Retry'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
